### ISSUE TITLE
Contributing file

### ISSUE THREAD

**Issue by noname07** [MatiasDurbano/TurbinaGame#3]
## Create a contributing file
 
- Steps for creating good issues and pull requests
- Links to external documentation
- Code of conduct
- Steps to clone and run it
- Other stuff

**Comment by abitsalihu** [comment]
Hey, I would like to help with this issue. :)

**Comment by noname07** [comment]
Thanks a lot c: Feel free to open a PR with the file.
I was expecting something like [this](https://github.com/github/docs/blob/main/CONTRIBUTING.md#pull-request) but feel free to improvise.
